In [183]:
#in this notebook we are going to do a descretization of differential equations
#this is a termo-dynamic equilibrium problem, in which the extreme values of the matrix are known, we have to find the values of the matrix in the middle

In [184]:
import numpy as np
import math

In [185]:
#in the functions fixos we are just calculating the values of the matrix in the extreme points
def fixos(matrix):
    size = matrix.shape[0]
    for i in reversed(range(size)):
        v = abs((i/(size-1))-1)
        matrix[i][0] = round(-(v**2),3)
        matrix[i][size-1] = round(1-(v**2),3)
    
    for i in range(0, size):
        v = i*(1/(size-1))#generalizando
        matrix[size-1][i] = round(v**2,3)
        matrix[0][i] = round((v**2) - 1,3)

def fixos_sem_arredondar(matrix):
    size = matrix.shape[0]
    for i in reversed(range(size)):
        v = abs((i/(size-1))-1)
        matrix[i][0] = -(v**2)
        matrix[i][size-1] = 1-(v**2)
    
    for i in range(0, size):
        v = i*(1/(size-1))#generalizando
        matrix[size-1][i] = v**2
        matrix[0][i] = (v**2) - 1

In [186]:
#now we are declaring the matrix, but be aware that the therms in the midle are not known yet
matrix = np.zeros((11,11))
matrix2 = matrix.copy()

#para qualquer que seja o n, adicione um, por exemplo, n = 5 -> 6x6

In [187]:
print(matrix) #antes

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [188]:
fixos(matrix)
matrix2 = matrix.copy()

In [189]:
print(matrix) #depois

[[-1.   -0.99 -0.96 -0.91 -0.84 -0.75 -0.64 -0.51 -0.36 -0.19  0.  ]
 [-0.81  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.19]
 [-0.64  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.36]
 [-0.49  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.51]
 [-0.36  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.64]
 [-0.25  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.75]
 [-0.16  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.84]
 [-0.09  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.91]
 [-0.04  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.96]
 [-0.01  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.99]
 [ 0.    0.01  0.04  0.09  0.16  0.25  0.36  0.49  0.64  0.81  1.  ]]


In [190]:
def solution(matrix):
    size = matrix.shape[0] #tamanho da matriz
    qtd_incognitas = (size-2)**2  #quantidade de incognitas

    equations = np.array([[]]) #parte da "esquerda" da equação, somente variáveis
    #remember that equations will be a 16x16 matrix
    values = np.array([]) #parte da "direita" da equação, somente valores

    #o indice 1 das equations tem igualdade com o indice 1 dos values, assim em diante
    
    matrix_aux = np.zeros((size, size)) #matriz auxiliar para guardar a nomenclatura de cada variável

    x = 1 #valor de inicio
    for i in reversed(range(1, size-1)):
        for j in range(1, size-1):
            matrix_aux[i][j] = x
            x += 1

    #agora, temos uma matriz com a nomenclatura de cada incognita, e a matriz com os valores do centro
    
    for i in reversed(range(1,size-1)):
        for j in range(1,size-1):
            x = matrix[i-1][j] #termo acima do central
            x2 = matrix[i][j+1] #termo a direita do central
            x3 = matrix[i+1][j] #termo abaixo do central
            x4 = matrix[i][j-1] #termo a esquerda do central

            a = np.zeros((1,qtd_incognitas))
            #print(len(a[0])) #exibindo o tamanho do vetor a
            #a linha acima serve para inicarmos uma equação do sistema linear com todos os coeficientes zerados
            total = 0
            #no if a seguir iremos verificar quais dos termos da borda são constantes
            if(i-1 == 0): #isso nos indica que o termo acima é uma constante, caso contrário é uma variável deve ser inserido no sistema linear como tal
                total += x
            else:
                indice = matrix_aux[i-1][j] #essa linha contém qual variável o [i-1][j] representa no sistema linear
                a[0][int(indice-1)] = -1 #aqui inserimos o coeficiente da variável no sistema linear
            if(i+1 == size-1):
                total += x3
            else:
                indice = matrix_aux[i+1][j]
                a[0][int(indice-1)] = -1
        
            if(j-1 == 0):
                total += x4
            else:
                indice = matrix_aux[i][j-1]
                a[0][int(indice-1)] = -1   
            
            if(j+1 == size-1):
                total += x2
            else:
                indice = matrix_aux[i][j+1]
                a[0][int(indice-1)] = -1
            
            #agora iremos adicionar 4x o termo central, pois multiplicamos ambos os lados por 4x
            a[0][int(matrix_aux[i][j]-1)] = 4
            #agora iremos inserir a equação que está armazenada em a ao sistema linear equations, em seu respectivo indice
            equations = np.append(equations, a)

            values = np.append(values, total)
    #vamos exibir a primeira equação armazenada no sistema linear equations
    #viewing the shape of the matrix
    equations = np.reshape(equations,(qtd_incognitas, qtd_incognitas))

    x = np.linalg.solve(equations, values)
    x = np.reshape(x, (size-2, size-2)) #reorganizando a resposta em uma matrix
    for i in range(size-2):
        for j in range(size-2):
            x[i][j] = x[i][j]
    #arredondando os valores para 3 casas decimais
    return x

In [191]:
def exact(matrix2):
    size = matrix2.shape[0]
    for i in reversed(range(1,size-1)):
        if i == size-2:
            y = (1/int(size-1))
        else: 
            y = abs((i/(size-1))-1)
        for j in range(1, size-1):
            x = j/(size-1)
            matrix2[i][j] = (x**2 - y**2)



In [192]:
exact(matrix2)

In [193]:
#print(matrix2)

In [194]:
respo = solution(matrix)
#a matrix está invertida, precisamos inverter ela, ou seja, a primeira linha deve ser a última.
respo = np.flip(respo, 0)
print(respo)

[[-8.00000000e-01 -7.70000000e-01 -7.20000000e-01 -6.50000000e-01
  -5.60000000e-01 -4.50000000e-01 -3.20000000e-01 -1.70000000e-01
   3.35587896e-17]
 [-6.30000000e-01 -6.00000000e-01 -5.50000000e-01 -4.80000000e-01
  -3.90000000e-01 -2.80000000e-01 -1.50000000e-01  5.98209891e-17
   1.70000000e-01]
 [-4.80000000e-01 -4.50000000e-01 -4.00000000e-01 -3.30000000e-01
  -2.40000000e-01 -1.30000000e-01  1.71630719e-17  1.50000000e-01
   3.20000000e-01]
 [-3.50000000e-01 -3.20000000e-01 -2.70000000e-01 -2.00000000e-01
  -1.10000000e-01  0.00000000e+00  1.30000000e-01  2.80000000e-01
   4.50000000e-01]
 [-2.40000000e-01 -2.10000000e-01 -1.60000000e-01 -9.00000000e-02
   5.13725085e-17  1.10000000e-01  2.40000000e-01  3.90000000e-01
   5.60000000e-01]
 [-1.50000000e-01 -1.20000000e-01 -7.00000000e-02  6.81419072e-17
   9.00000000e-02  2.00000000e-01  3.30000000e-01  4.80000000e-01
   6.50000000e-01]
 [-8.00000000e-02 -5.00000000e-02  5.05281268e-17  7.00000000e-02
   1.60000000e-01  2.7000000

In [195]:
#para verificar mais facilmente se a solução está correta, vamos excluir a primeira e útlima colunas da matrix2, além da primeira e última linha
size = matrix2.shape[0]
matrix2 = np.delete(matrix2, 0, 0)
matrix2 = np.delete(matrix2, size-2, 0)
matrix2 = np.delete(matrix2, 0, 1)
matrix2 = np.delete(matrix2, size-2, 1)
print(matrix2)
print(matrix2.shape)

[[-8.00000000e-01 -7.70000000e-01 -7.20000000e-01 -6.50000000e-01
  -5.60000000e-01 -4.50000000e-01 -3.20000000e-01 -1.70000000e-01
   0.00000000e+00]
 [-6.30000000e-01 -6.00000000e-01 -5.50000000e-01 -4.80000000e-01
  -3.90000000e-01 -2.80000000e-01 -1.50000000e-01  0.00000000e+00
   1.70000000e-01]
 [-4.80000000e-01 -4.50000000e-01 -4.00000000e-01 -3.30000000e-01
  -2.40000000e-01 -1.30000000e-01  0.00000000e+00  1.50000000e-01
   3.20000000e-01]
 [-3.50000000e-01 -3.20000000e-01 -2.70000000e-01 -2.00000000e-01
  -1.10000000e-01  0.00000000e+00  1.30000000e-01  2.80000000e-01
   4.50000000e-01]
 [-2.40000000e-01 -2.10000000e-01 -1.60000000e-01 -9.00000000e-02
   0.00000000e+00  1.10000000e-01  2.40000000e-01  3.90000000e-01
   5.60000000e-01]
 [-1.50000000e-01 -1.20000000e-01 -7.00000000e-02  0.00000000e+00
   9.00000000e-02  2.00000000e-01  3.30000000e-01  4.80000000e-01
   6.50000000e-01]
 [-8.00000000e-02 -5.00000000e-02 -2.77555756e-17  7.00000000e-02
   1.60000000e-01  2.7000000

In [196]:
#para achar o erro iremos somar todos os valores absolutos da diferença entre a solução e a resposta exata
erro = 0
sumrespo = 0
summatrix = 0
#iremos usar len(respo) porque as duas matrizes tem o mesmo tamanho agora
for i in range(len(respo)):
    for j in range(len(respo)):
        sumrespo = sumrespo + abs(respo[i][j])
        summatrix = summatrix + abs(matrix2[i][j])

erro = abs(sumrespo - summatrix)

print(erro)

3.552713678800501e-15
