In [1016]:
#in this notebook we are going to do a descretization of differential equations
#this is a termo-dynamic equilibrium problem, in which the extreme values of the matrix are known, we have to find the values of the matrix in the middle

In [1017]:
import numpy as np
import math

In [1018]:
#in the functions fixos we are just calculating the values of the matrix in the extreme points
def fixos(matrix):
    size = matrix.shape[0]
    for i in reversed(range(size)):
        v = abs((i/(size-1))-1)
        matrix[i][0] = round(-(v**2),3)
        matrix[i][size-1] = round(1-(v**2),3)
    
    for i in range(0, size):
        v = i*(1/(size-1))#generalizando
        matrix[size-1][i] = round(v**2,3)
        matrix[0][i] = round((v**2) - 1,3)

In [1019]:
#now we are declaring the matrix, but be aware that the therms in the midle are not known yet
matrix = np.zeros((21,21))
matrix2 = matrix.copy()

#para qualquer que seja o n, adicione um, por exemplo, n = 5 -> 6x6

In [1020]:
print(matrix) #antes

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0.

In [1021]:
fixos(matrix)
matrix2 = matrix.copy()

In [1022]:
print(matrix) #depois

[[-1.    -0.998 -0.99  -0.978 -0.96  -0.938 -0.91  -0.877 -0.84  -0.797
  -0.75  -0.698 -0.64  -0.577 -0.51  -0.438 -0.36  -0.277 -0.19  -0.097
   0.   ]
 [-0.902  0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.098]
 [-0.81   0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.19 ]
 [-0.722  0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.278]
 [-0.64   0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.36 ]
 [-0.562  0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.438]
 [-0.49   0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.     0.     0.     0.     0.    

In [1023]:
def solution(matrix):
    size = matrix.shape[0] #tamanho da matriz
    qtd_incognitas = (size-2)**2  #quantidade de incognitas

    equations = np.array([[]]) #parte da "esquerda" da equação, somente variáveis
    #remember that equations will be a 16x16 matrix
    values = np.array([]) #parte da "direita" da equação, somente valores

    #o indice 1 das equations tem igualdade com o indice 1 dos values, assim em diante
    
    matrix_aux = np.zeros((size, size)) #matriz auxiliar para guardar a nomenclatura de cada variável

    x = 1 #valor de inicio
    for i in reversed(range(1, size-1)):
        for j in range(1, size-1):
            matrix_aux[i][j] = x
            x += 1

    #agora, temos uma matriz com a nomenclatura de cada incognita, e a matriz com os valores do centro
    
    for i in reversed(range(1,size-1)):
        for j in range(1,size-1):
            x = matrix[i-1][j] #termo acima do central
            x2 = matrix[i][j+1] #termo a direita do central
            x3 = matrix[i+1][j] #termo abaixo do central
            x4 = matrix[i][j-1] #termo a esquerda do central

            a = np.zeros((1,qtd_incognitas))
            #print(len(a[0])) #exibindo o tamanho do vetor a
            #a linha acima serve para inicarmos uma equação do sistema linear com todos os coeficientes zerados
            total = 0
            #no if a seguir iremos verificar quais dos termos da borda são constantes
            if(i-1 == 0): #isso nos indica que o termo acima é uma constante, caso contrário é uma variável deve ser inserido no sistema linear como tal
                total += x
            else:
                indice = matrix_aux[i-1][j] #essa linha contém qual variável o [i-1][j] representa no sistema linear
                a[0][int(indice-1)] = -1 #aqui inserimos o coeficiente da variável no sistema linear
            if(i+1 == size-1):
                total += x3
            else:
                indice = matrix_aux[i+1][j]
                a[0][int(indice-1)] = -1
        
            if(j-1 == 0):
                total += x4
            else:
                indice = matrix_aux[i][j-1]
                a[0][int(indice-1)] = -1   
            
            if(j+1 == size-1):
                total += x2
            else:
                indice = matrix_aux[i][j+1]
                a[0][int(indice-1)] = -1
            
            #agora iremos adicionar 4x o termo central, pois multiplicamos ambos os lados por 4x
            a[0][int(matrix_aux[i][j]-1)] = 4
            #agora iremos inserir a equação que está armazenada em a ao sistema linear equations, em seu respectivo indice
            equations = np.append(equations, a)

            values = np.append(values, total)
    #vamos exibir a primeira equação armazenada no sistema linear equations
    #viewing the shape of the matrix
    equations = np.reshape(equations,(qtd_incognitas, qtd_incognitas))

    x = np.linalg.solve(equations, values)
    x = np.reshape(x, (size-2, size-2)) #reorganizando a resposta em uma matrix
    for i in range(size-2):
        for j in range(size-2):
            x[i][j] = round(x[i][j], 3)
    #arredondando os valores para 3 casas decimais
    return x

In [1024]:
def exact(matrix2):
    size = matrix2.shape[0]
    for i in reversed(range(1,size-1)):
        if i == size-2:
            y = (1/int(size-1))
        else: 
            y = abs((i/(size-1))-1)
        for j in range(1, size-1):
            x = j/(size-1)
            matrix2[i][j] = round((x**2 - y**2), 3)



In [1025]:
exact(matrix2)

In [1026]:
print(matrix2)

[[-1.    -0.998 -0.99  -0.978 -0.96  -0.938 -0.91  -0.877 -0.84  -0.797
  -0.75  -0.698 -0.64  -0.577 -0.51  -0.438 -0.36  -0.277 -0.19  -0.097
   0.   ]
 [-0.902 -0.9   -0.892 -0.88  -0.862 -0.84  -0.812 -0.78  -0.742 -0.7
  -0.652 -0.6   -0.542 -0.48  -0.413 -0.34  -0.262 -0.18  -0.092  0.
   0.098]
 [-0.81  -0.808 -0.8   -0.788 -0.77  -0.748 -0.72  -0.688 -0.65  -0.608
  -0.56  -0.508 -0.45  -0.388 -0.32  -0.248 -0.17  -0.088  0.     0.092
   0.19 ]
 [-0.722 -0.72  -0.712 -0.7   -0.682 -0.66  -0.632 -0.6   -0.562 -0.52
  -0.472 -0.42  -0.362 -0.3   -0.232 -0.16  -0.082  0.     0.088  0.18
   0.278]
 [-0.64  -0.638 -0.63  -0.618 -0.6   -0.578 -0.55  -0.518 -0.48  -0.438
  -0.39  -0.338 -0.28  -0.218 -0.15  -0.078  0.     0.082  0.17   0.262
   0.36 ]
 [-0.562 -0.56  -0.552 -0.54  -0.522 -0.5   -0.473 -0.44  -0.402 -0.36
  -0.312 -0.26  -0.203 -0.14  -0.073  0.     0.078  0.16   0.248  0.34
   0.438]
 [-0.49  -0.487 -0.48  -0.467 -0.45  -0.427 -0.4   -0.367 -0.33  -0.287
  -0.24  -0.1

In [1027]:
respo = solution(matrix)
#a matrix está invertida, precisamos inverter ela, ou seja, a primeira linha deve ser a última.
respo = np.flip(respo, 0)
print(respo)
print(respo.shape)

[[-0.9   -0.893 -0.88  -0.863 -0.84  -0.812 -0.78  -0.742 -0.7   -0.652
  -0.6   -0.542 -0.48  -0.412 -0.34  -0.262 -0.18  -0.092  0.   ]
 [-0.807 -0.8   -0.788 -0.77  -0.748 -0.72  -0.687 -0.65  -0.607 -0.56
  -0.507 -0.45  -0.387 -0.32  -0.247 -0.17  -0.087  0.     0.093]
 [-0.72  -0.712 -0.7   -0.683 -0.66  -0.632 -0.6   -0.562 -0.52  -0.472
  -0.42  -0.362 -0.3   -0.232 -0.16  -0.082  0.     0.088  0.18 ]
 [-0.637 -0.63  -0.617 -0.6   -0.577 -0.55  -0.517 -0.48  -0.437 -0.39
  -0.337 -0.28  -0.217 -0.15  -0.077  0.     0.083  0.17   0.263]
 [-0.56  -0.552 -0.54  -0.522 -0.5   -0.472 -0.44  -0.402 -0.36  -0.312
  -0.26  -0.202 -0.14  -0.072  0.     0.078  0.16   0.248  0.34 ]
 [-0.487 -0.48  -0.467 -0.45  -0.427 -0.4   -0.367 -0.33  -0.287 -0.24
  -0.187 -0.13  -0.067  0.     0.073  0.15   0.233  0.32   0.413]
 [-0.42  -0.413 -0.4   -0.382 -0.36  -0.332 -0.3   -0.262 -0.22  -0.172
  -0.12  -0.062  0.     0.068  0.14   0.218  0.3    0.388  0.48 ]
 [-0.358 -0.35  -0.338 -0.32  -0.297 

In [1028]:
#para verificar mais facilmente se a solução está correta, vamos excluir a primeira e útlima colunas da matrix2, além da primeira e última linha
size = matrix2.shape[0]
matrix2 = np.delete(matrix2, 0, 0)
matrix2 = np.delete(matrix2, size-2, 0)
matrix2 = np.delete(matrix2, 0, 1)
matrix2 = np.delete(matrix2, size-2, 1)
print(matrix2)
print(matrix2.shape)

[[-0.9   -0.892 -0.88  -0.862 -0.84  -0.812 -0.78  -0.742 -0.7   -0.652
  -0.6   -0.542 -0.48  -0.413 -0.34  -0.262 -0.18  -0.092  0.   ]
 [-0.808 -0.8   -0.788 -0.77  -0.748 -0.72  -0.688 -0.65  -0.608 -0.56
  -0.508 -0.45  -0.388 -0.32  -0.248 -0.17  -0.088  0.     0.092]
 [-0.72  -0.712 -0.7   -0.682 -0.66  -0.632 -0.6   -0.562 -0.52  -0.472
  -0.42  -0.362 -0.3   -0.232 -0.16  -0.082  0.     0.088  0.18 ]
 [-0.638 -0.63  -0.618 -0.6   -0.578 -0.55  -0.518 -0.48  -0.438 -0.39
  -0.338 -0.28  -0.218 -0.15  -0.078  0.     0.082  0.17   0.262]
 [-0.56  -0.552 -0.54  -0.522 -0.5   -0.473 -0.44  -0.402 -0.36  -0.312
  -0.26  -0.203 -0.14  -0.073  0.     0.078  0.16   0.248  0.34 ]
 [-0.487 -0.48  -0.467 -0.45  -0.427 -0.4   -0.367 -0.33  -0.287 -0.24
  -0.187 -0.13  -0.067  0.     0.073  0.15   0.232  0.32   0.413]
 [-0.42  -0.413 -0.4   -0.383 -0.36  -0.333 -0.3   -0.263 -0.22  -0.173
  -0.12  -0.063  0.     0.067  0.14   0.218  0.3    0.388  0.48 ]
 [-0.357 -0.35  -0.337 -0.32  -0.297 

In [1029]:
#para achar o erro iremos somar todos os valores absolutos da diferença entre a solução e a resposta exata
erro = 0
#iremos usar len(respo) porque as duas matrizes tem o mesmo tamanho agora
for i in range(len(respo)):
    for j in range(len(respo)):
        erro += abs(respo[i][j]-matrix2[i][j])

print(erro)

0.08599999999999974
