In [16]:
#in this notebook we are going to do a descretization of differential equations
#this is a termo-dynamic equilibrium problem, in which the extreme values of the matrix are known, we have to find the values of the matrix in the middle

In [17]:
import numpy as np
import math

In [18]:
#in the functions fixos we are just calculating the values of the matrix in the extreme points
def fixos(matrix):
    size = matrix.shape[0]
    for i in reversed(range(size)):
        v = abs((i/(size-1))-1)
        matrix[i][0] = round(-(v**2),3)
        matrix[i][size-1] = round(1-(v**2),3)
    
    for i in range(0, size):
        v = i*(1/(size-1))#generalizando
        matrix[size-1][i] = round(v**2,3)
        matrix[0][i] = round((v**2) - 1,3)

#in the function discretize we are calculating the values of the matrix in the middle points, a point is the average of the four points around it
def discretize(matrix):
    size = matrix.shape[0]
    for i in range(1, size-1):
        for j in range(1, size-1):
            matrix[i][j] = round((matrix[i+1][j] + matrix[i-1][j] + matrix[i][j+1] + matrix[i][j-1])/4,3)

In [19]:
#now we are declaring the matrix, but be aware that the therms in the midle are not known yet
matrix = np.ones((11,11))

#para qualquer que seja o n, adicione um, por exemplo, n = 5 -> 6x6

In [20]:
print(matrix) #antes

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [21]:
fixos(matrix) #função
matrix2 = matrix.copy()

In [22]:
print(matrix) #depois

[[-1.   -0.99 -0.96 -0.91 -0.84 -0.75 -0.64 -0.51 -0.36 -0.19  0.  ]
 [-0.81  1.    1.    1.    1.    1.    1.    1.    1.    1.    0.19]
 [-0.64  1.    1.    1.    1.    1.    1.    1.    1.    1.    0.36]
 [-0.49  1.    1.    1.    1.    1.    1.    1.    1.    1.    0.51]
 [-0.36  1.    1.    1.    1.    1.    1.    1.    1.    1.    0.64]
 [-0.25  1.    1.    1.    1.    1.    1.    1.    1.    1.    0.75]
 [-0.16  1.    1.    1.    1.    1.    1.    1.    1.    1.    0.84]
 [-0.09  1.    1.    1.    1.    1.    1.    1.    1.    1.    0.91]
 [-0.04  1.    1.    1.    1.    1.    1.    1.    1.    1.    0.96]
 [-0.01  1.    1.    1.    1.    1.    1.    1.    1.    1.    0.99]
 [ 0.    0.01  0.04  0.09  0.16  0.25  0.36  0.49  0.64  0.81  1.  ]]


In [23]:
def teste(matrix):
    #now we are going to solve the linear system, we are going to use the gauss method
    size = matrix.shape[0]
    qtd_incognitas = (size-2)**2 
    #creating a matrix with the size of incognitas
    equations = np.array([[]])
    values = np.array([])
    # no loop abaixo nos certificamos que iremos obter somente os termos do centro.
    for i in reversed(range(1,size-1)):
        for j in range(1,size-1):
            #agora iremos começar a montar o sistema linear, lembrando que o valor em ponto é a média aritimética dos pontos ao redor dele
            #a quantidade de incognias é sempre (size-2)**2
            #usando a biblioteca de sistemas lineares do numpy, podemos resolver o mesmo
            #por exemplo, chamando o termo matrix[1][1] de x, o termo matrix[1][2] de x2, o termo matrix[2][1] de x3
            #acharemos que x = (x2 + x3 + x4 + x5)/4 nos quais x4 e x5 são os termos definidos da fronteira, contudo, se o termo fosse central esses outros também
            #seriam variáveis
            #iremos declarar o x1 como o termo acima do x, o x2 como o termo a direita do x, o x3 como o termo abaixo do x e o x4 como o termo a esquerda do x
            x = matrix[i-1][j] #-1 ao invés de 1 pq começamos invertidos
            x2 = matrix[i][j+1]
            x3 = matrix[i+1][j]
            x4 = matrix[i][j-1]

            a = np.zeros((1,qtd_incognitas))
            #a linha acima serve para inicarmos uma equação do sistema linear com todos os coeficientes zerados
            total = 0
            #no if a seguir iremos verificar quais dos termos da borda são constantes

            if(i-1 == 0 or j-1 == 0 or j+1 == size-1 or i+1 == size-1):
                if(i-1 == 0):
                    total = total + x
                if(j-1 == 0):
                    total = total + x4
                if(j+1 == size-1):
                    total = total + x2
                if(i+1 == size-1):
                    total = total + x3
            
            values = np.append(values, total)
            # a parte de cima está workando

            #we are going to insert the values that are not known yet in the equations
    
        


            #o array equations conterá as variáveis de incognita, e o array values conterá os valores definidos(fronteiras), caso o termo seja central, o valor será 0
            #lembrando que eles são correspondente com os indices



            #agora iremos montar o sistema linear
            #temos 16 incognitas, logo, 16 equações, todas as equações devem conter todos os termos, mesmos que com coeficiente 0, para que o sistema seja resolvido
            
            #lembrando que a matrix equations possue o lado esquerdo da igualdado, e a matrix values o lado direito, ou seja, podemos manter somente a variável
            #que nos interessa na matrix equations, e os outros termos na matrix values, respeitando a ordem
            #we have to fill the np array with zeros, except the therm that has the index equal to i, this index is going to be equal to 4
            #for k in range((size-2)**2):
            #    if k == (i-1):
            #        a = np.append(a, 4)
            #    else:
            #        a = np.append(a, 0)
            
            #a linha acima nos garante que teremos a 4x a variável que queremos no lado esquerdo da equação, e do lado direito os termos os quais dependemos 
    print(values)

    #vamos fazer o loop ao contrário, visto que
         



In [24]:
discretize(matrix)

In [25]:
print(matrix) #depois

[[-1.    -0.99  -0.96  -0.91  -0.84  -0.75  -0.64  -0.51  -0.36  -0.19
   0.   ]
 [-0.81   0.05   0.272  0.34   0.375  0.406  0.442  0.483  0.531  0.383
   0.19 ]
 [-0.64   0.352  0.656  0.749  0.781  0.797  0.81   0.823  0.838  0.645
   0.36 ]
 [-0.49   0.465  0.78   0.882  0.916  0.928  0.934  0.939  0.944  0.775
   0.51 ]
 [-0.36   0.526  0.826  0.927  0.961  0.972  0.976  0.979  0.981  0.849
   0.64 ]
 [-0.25   0.569  0.849  0.944  0.976  0.987  0.991  0.992  0.993  0.898
   0.75 ]
 [-0.16   0.602  0.863  0.952  0.982  0.992  0.996  0.997  0.997  0.934
   0.84 ]
 [-0.09   0.628  0.873  0.956  0.984  0.994  0.998  0.999  0.999  0.961
   0.91 ]
 [-0.04   0.647  0.88   0.959  0.986  0.995  0.998  0.999  1.     0.98
   0.96 ]
 [-0.01   0.412  0.583  0.658  0.701  0.736  0.774  0.816  0.864  0.911
   0.99 ]
 [ 0.     0.01   0.04   0.09   0.16   0.25   0.36   0.49   0.64   0.81
   1.   ]]


In [26]:
#now we are going the exact matrix, we know that the values in each point respect te function f(x,y) = x^2 - y^2
def exact(matrix2):
    size = matrix2.shape[0]
    for i in reversed(range(1,size-1)):
        if i == size-2:
            y = (1/int(size-1))
        else: 
            y = abs((i/(size-1))-1)
        for j in range(1, size-1):
            x = j/(size-1)
            matrix2[i][j] = round((x**2 - y**2), 3)



In [27]:
exact(matrix2)

In [28]:
print(matrix2)

[[-1.   -0.99 -0.96 -0.91 -0.84 -0.75 -0.64 -0.51 -0.36 -0.19  0.  ]
 [-0.81 -0.8  -0.77 -0.72 -0.65 -0.56 -0.45 -0.32 -0.17  0.    0.19]
 [-0.64 -0.63 -0.6  -0.55 -0.48 -0.39 -0.28 -0.15  0.    0.17  0.36]
 [-0.49 -0.48 -0.45 -0.4  -0.33 -0.24 -0.13  0.    0.15  0.32  0.51]
 [-0.36 -0.35 -0.32 -0.27 -0.2  -0.11  0.    0.13  0.28  0.45  0.64]
 [-0.25 -0.24 -0.21 -0.16 -0.09  0.    0.11  0.24  0.39  0.56  0.75]
 [-0.16 -0.15 -0.12 -0.07  0.    0.09  0.2   0.33  0.48  0.65  0.84]
 [-0.09 -0.08 -0.05 -0.    0.07  0.16  0.27  0.4   0.55  0.72  0.91]
 [-0.04 -0.03  0.    0.05  0.12  0.21  0.32  0.45  0.6   0.77  0.96]
 [-0.01  0.    0.03  0.08  0.15  0.24  0.35  0.48  0.63  0.8   0.99]
 [ 0.    0.01  0.04  0.09  0.16  0.25  0.36  0.49  0.64  0.81  1.  ]]


In [29]:
teste(matrix2)

[ 0.    0.04  0.09  0.16  0.25  0.36  0.49  0.64  1.8  -0.04  0.    0.
  0.    0.    0.    0.    0.    0.96 -0.09  0.    0.    0.    0.    0.
  0.    0.    0.91 -0.16  0.    0.    0.    0.    0.    0.    0.    0.84
 -0.25  0.    0.    0.    0.    0.    0.    0.    0.75 -0.36  0.    0.
  0.    0.    0.    0.    0.    0.64 -0.49  0.    0.    0.    0.    0.
  0.    0.    0.51 -0.64  0.    0.    0.    0.    0.    0.    0.    0.36
 -1.8  -0.96 -0.91 -0.84 -0.75 -0.64 -0.51 -0.36  0.  ]


In [30]:
print(matrix2)

[[-1.   -0.99 -0.96 -0.91 -0.84 -0.75 -0.64 -0.51 -0.36 -0.19  0.  ]
 [-0.81 -0.8  -0.77 -0.72 -0.65 -0.56 -0.45 -0.32 -0.17  0.    0.19]
 [-0.64 -0.63 -0.6  -0.55 -0.48 -0.39 -0.28 -0.15  0.    0.17  0.36]
 [-0.49 -0.48 -0.45 -0.4  -0.33 -0.24 -0.13  0.    0.15  0.32  0.51]
 [-0.36 -0.35 -0.32 -0.27 -0.2  -0.11  0.    0.13  0.28  0.45  0.64]
 [-0.25 -0.24 -0.21 -0.16 -0.09  0.    0.11  0.24  0.39  0.56  0.75]
 [-0.16 -0.15 -0.12 -0.07  0.    0.09  0.2   0.33  0.48  0.65  0.84]
 [-0.09 -0.08 -0.05 -0.    0.07  0.16  0.27  0.4   0.55  0.72  0.91]
 [-0.04 -0.03  0.    0.05  0.12  0.21  0.32  0.45  0.6   0.77  0.96]
 [-0.01  0.    0.03  0.08  0.15  0.24  0.35  0.48  0.63  0.8   0.99]
 [ 0.    0.01  0.04  0.09  0.16  0.25  0.36  0.49  0.64  0.81  1.  ]]
